name: Application testing

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v3 
              with:
                python-version: "3.9"
            - name: Installing dependencies 
              run: 
                pip install -r requirements.txt
            - name: Running api testcases
              run:
                pytest test_api.py 
            - name: Running model testcase 
              run: 
                pytest test_model.py 
            

        


            
            